/*
 * TIMER1_config.h
 *
 * Created: 21-Dec-23 9:17:30 AM
 *  Author: MICHAEL
 */ 


#ifndef TIMER1_CONFIG_H_
#define TIMER1_CONFIG_H_


/* Options:
	TIMER
	COUNTER
 */
#define TIMER1_COUNTER_MODE	TIMER
 
/*
Counter options:
	1-COUNTER1_SENSE_RISING
	2-COUNTER1_SENSE_FALLING
*/
#define COUNTER1_SENSE	COUNTER1_SENSE_RISING

 
 /* TIMER0 Prescalar Options*/
 /*
 *  1- TIMER1_PRESCALER_1
 *  2- TIMER1_PRESCALER_8
 *  3- TIMER1_PRESCALER_64
 *  4- TIMER1_PRESCALER_256
 *  5- TIMER1_PRESCALER_1024

 */
 #define TIMER1_PRESCALER TIMER1_PRESCALER_8


 /* TIMER0 Mode options
	1-TIMER1_NORMAL_MODE
	2-TIMER1_PHASE_CORRECT_PWM_8BIT
	3-TIMER1_PHASE_CORRECT_PWM_9BIT
	4-TIMER1_PHASE_CORRECT_PWM_10BIT
	5-TIMER1_CTC_MODE_OCR1A
	6-TIMER1_FAST_PWM_8BIT
	7-TIMER1_FAST_PWM_9BIT
	8-TIMER1_FAST_PWM_10BIT
	9-TIMER1_PHASE_FREQ_CORRECT_PWM_ICR1
	10-TIMER1_PHASE_FREQ_CORRECT_PWM_OCR1A
	11-TIMER1_PHASE_CORRECT_PWM_ICR1
	12-TIMER1_PHASE_CORRECT_PWM_OCR1A
	14-TIMER1_CTC_MODE_ICR1
	15-TIMER1_FAST_PWM_ICR1
	16-TIMER1_FAST_PWM_OCR1A
*/
#define TIMER1_MODE TIMER1_FAST_PWM_OCR1A


/*
	OC1A options in CTC mode
		1-CTC_OC1A_DISABLE
		2-CTC_OC1A_TOOGLE
		3-CTC_OC1A_CLEAR
		4-CTC_OC1A_SET		
*/
#define CTC_OC1A_PIN			CTC_OC1A_DISABLE

/*
	OC1B options in CTC mode
		1-CTC_OC1B_DISABLE
		2-CTC_OC1B_TOOGLE
		3-CTC_OC1B_CLEAR
		4-CTC_OC1B_SET
*/
#define CTC_OC1B_PIN			CTC_OC1B_DISABLE

/*
	OC1A options in PWM mode
		1-PWM_OC1A_DISABLE
		2-PWM_OC1A_TOOGLE
		3-PWM_OC1A_NON_INVERTED
		4-PWM_OC1A_INVERTED		
*/
#define PWM_OC1A_PIN			PWM_OC1A_NON_INVERTED

/*
	OC1B options in PWM mode
		1-PWM_OC1B_DISABLE
		2-PWM_OC1B_TOOGLE
		3-PWM_OC1B_NON_INVERTED
		4-PWM_OC1B_INVERTED		
*/
#define PWM_OC1B_PIN			PWM_OC1B_NON_INVERTED


#endif /* TIMER1_CONFIG_H_ */